// Code generated by `go generate`; DO NOT EDIT.

package kokr

type ItemCodeResolver struct {
	localeNames map[string]string
}

func NewItemCodeResolver() ItemCodeResolver {
	return ItemCodeResolver{
		localeNames: map[string]string{

			"0000": "대파",
		},
	}
}

func (r ItemCodeResolver) SupportedCodes() map[string]string {
	return r.localeNames
}

func (r ItemCodeResolver) ResolveCode(c string) (string, bool) {
	localeName, ok := r.localeNames[c]
	return localeName, ok
}
