// Code generated by `go generate`; DO NOT EDIT.

package kokr

type RegionCodeResolver struct {
	localeNames map[string]string
}

func NewRegionCodeResolver() RegionCodeResolver {
	return RegionCodeResolver{
		localeNames: map[string]string{

			"0000": "서울",
		},
	}
}

func (r RegionCodeResolver) SupportedCodes() map[string]string {
	return r.localeNames
}

func (r RegionCodeResolver) ResolveCode(c string) (string, bool) {
	localeName, ok := r.localeNames[c]
	return localeName, ok
}
